server:
    port: 8761
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8765/eureka
spring:
    application:
        name: api-gateway
    #cloud:
        #gateway:
            #discovery:
                #locator:
                    #enabled: true
                    #lower-case-service-id: true